# Generated by Django 4.2.14 on 2025-10-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='pharmacyitem',
            old_name='count',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='pharmacompany',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyitem',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
