# Generated by Django 4.2.14 on 2025-10-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_insurancecompany_rename_count_pharmacyitem_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pharmacyitem',
            name='locked',
        ),
    ]
