# Generated by Django 4.2.14 on 2025-10-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0003_remove_pharmacy_user_remove_pharmacyitem_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pharmacy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyitem')),
            ],
        ),
    ]
